"""
Crew Orchestration Module.

This module is responsible for assembling the AI team (Crew), assigning them 
their specific tasks, and managing the execution flow. It serves as the 
entry point for the agentic workflow.

Key Responsibilities:
    - Instantiating Agents and Tasks.
    - Configuring the CrewAI execution process (Sequential).
    - Handling the 'kickoff' to start the analysis.
"""

from crewai import Crew, Process
from src.agents.agents import create_agents
from src.agents.tasks import create_tasks

def run_financial_crew(ticker: str) -> str:
    """
    Initializes and executes the Financial Analysis Crew for a specific stock.

    Args:
        ticker (str): The stock symbol to analyze (e.g., 'MSFT').

    Returns:
        str: The final markdown report generated by the Strategist agent.
    """
    
    # 1. Hire the Team (Instantiate Agents)
    # Note: The order here doesn't determine execution order, just assignment.
    quant_agent, strategist_agent = create_agents()
    
    # 2. Assign the Work (Create Tasks)
    # Note: We pass the specific ticker symbol here so the prompts are dynamic.
    tasks = create_tasks(
        quant_agent=quant_agent,
        strategist_agent=strategist_agent,
        ticker=ticker
    )
    
    # 3. Assemble the Crew
    # We use Process.sequential to ensure the Quant finishes BEFORE the Strategist starts.
    financial_crew = Crew(
        agents=[quant_agent, strategist_agent],
        tasks=tasks,
        process=Process.sequential,
        verbose=True,  # Logs every step to the console (great for debugging)
        memory=False,   # Enables agents to remember past interactions,
        tracing=False   # Enables LangSmith tracing for the entire crew
    )
    
    # 4. Start the Job
    print(f"\n🚀 Kicking off Financial Analysis for {ticker}...")
    result = financial_crew.kickoff()
    
    return result